# Generated by Django 5.0.14 on 2026-03-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_rename_created_at_post_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
