# Generated by Django 5.0.14 on 2026-03-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default="untitled-post", max_length=250, unique_for_date="publish"
            ),
            preserve_default=False,
        ),
    ]
