# Generated by Django 6.0.5 on 2026-05-08 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="users_like",
            field=models.ManyToManyField(
                blank=True, related_name="images_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
